### ISSUE TITLE
Not able to use pytest_watcher along with VS Code debugpy

### ISSUE THREAD

**Issue by gabriel-abn** [olzhasar/pytest-watcher#28] opened 2024-02-21 13:11 UTC
Hello guys... I'm not sure if this issue should be assigned here, but since _watcher_ is the only thing that is raising something when trying to debug tests I think it is in the right place.

#### I have this configuration setup to run debug mode on a opened file:

![Screenshot from 2024-02-21 09-30-57](https://github.com/olzhasar/pytest-watcher/assets/29826297/6a397a0a-5846-4bef-a904-00ce3d0fee66)

I'm trying to run VS Code debug mode along with _watcher_ but I'm getting some annoying errors. I had set this debug config above to run **pytest_watcher in debug mode** but it has some different behaviors for some scenarios:

- If I set `"console": "integratedTerminal"`, it only works if I activate a virtual environment in an already opened console before running the debug mode but it _skips all breakpoints_.
- If I set `"console": "externalTerminal"` or just let the last config without activating my _venv_ it stops inside _ptw_ script and raises the following error:

![Screenshot from 2024-02-21 09-24-31](https://github.com/olzhasar/pytest-watcher/assets/29826297/82eb0365-d83d-46bf-9325-08e70d4dbf2f)

**I'm opting to use the old _pytest-watch_ for debug mode. It is working just fine.** If I switch to simple _python_ debug configuration type ( `"type": "python"` ), it runs fine but it skips all breakpoints. Opting to use _debugpy_ because the simple one will be deprecated soon.

- VS Code: 1.86.2
- Python: 3.11.7
- Pytest: 8.0.1 (but the same thing was happening with 7.4.0)
- Pytest-watcher: 0.4.1
- Debugpy Extension: 2024.0.0

#### This is the code snippet I'm trying to debug:

![image](https://github.com/olzhasar/pytest-watcher/assets/29826297/59683e9a-fc98-4429-b23a-b8bab80401da)

#### Some other plugins I use along Pytest:

![image](https://github.com/olzhasar/pytest-watcher/assets/29826297/1795dbc8-789c-421e-9fff-d599c8a153c8)

----
## Some of the things I've tried

- The obvious: remade my _venv_ folder.
- Absolute path to all configs (_program_, _python_, _cwd_, etc.)
- Removed coverage report in _addopts_ section in _pytest.ini_ file or by env variable.
- Changed my workspace default interpreter.

**Comment by olzhasar** [comment] 2024-02-21 18:57
Hi,

I am not familiar with debugpy and cannot provide any assistance with that.  You should check your IDE configuration to run packages from your `venv`, cause that seems to be the problem.

I am closing this issue as unrelated to the functionality of `pytest-watcher`. Feel free to reopen if you find some explicit conflicts caused by the library's code.

**Closed by olzhasar** 2024-02-21 18:57 UTC

**Comment by gabriel-abn** [comment] 2024-02-21 19:46
Ok, I'm gonna keep looking forward on **_venv_** usage in VS Code and using **_pytest-watch_** til I fix it all. As I said, _pytest-watch_ allows me to debug and watch the breakpoints just as it should do but I didn't find out something to fix this yet.

If I find something that may start some solution I get back here and decide if I either reopen it or just comment to make it public.
